app/config/urls.py
"""config URL Configuration for the project
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from main.views import ProfileView

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('diary/', include('diary.urls')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='main:index'), name='logout'),
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lessons/', include('lessons.urls')),
]

app/diary/urls.py
from django.urls import path

from .views import DateListView, DiaryEntryView, diary_entry_success

app_name = 'diary'

urlpatterns = [
    path('entry/', DiaryEntryView.as_view(), name='diary-entry'),
    # Добавляем путь с параметром для даты
    # path('entry/<slug:date>/', DiaryEntryView.as_view(), name='diary-entry-date'),
    path('entry/success/', diary_entry_success, name='diary-entry-success'),
    path('date-list/', DateListView.as_view(), name='date-list'),
]

app/main/urls.py
from django.urls import path

from .views import ContactView, CourseView, IndexView, SiteErrorView

# AboutView,

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('index/', IndexView.as_view(), name='index'),
    path('course/', CourseView.as_view(), name='course'),
    path('contact/', ContactView.as_view(), name='contact'),
    # path('profile/', ProfileView.as_view(), name='profile'),
    path('site_error/', SiteErrorView.as_view(), name='site_error'),
]

app/diary/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class DiaryEntry(models.Model):
    date = models.DateField()
    steps = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100000)])
    study_hours = models.IntegerField()

    def __str__(self):
        return str(self.date)

app/diary/forms.py
from datetime import datetime

from django import forms
from django.conf import settings
from django.forms.widgets import DateInput

from .models import DiaryEntry


class DiaryEntryForm(forms.ModelForm):
    # date = forms.DateField(
    #     widget=forms.DateInput(format='%d/%m/%Y'),
    #     input_formats=['%d/%m/%Y'],
    #     # widget=forms.DateInput(attrs={'type': 'date', 'format': '%d/%m/%Y'})
    # )

    date = forms.DateField(
        widget=forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control'}),
        input_formats=['%d/%m/%Y'],
    )
    steps = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
    )
    study_hours = forms.DecimalField(
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = DiaryEntry
        fields = ['date', 'steps', 'study_hours']

    def clean_steps(self):
        steps = self.cleaned_data['steps']
        if not isinstance(steps, int):
            raise forms.ValidationError('Количество шагов должно быть числом.')
        return steps

    def clean_study_hours(self):
        study_hours = self.cleaned_data['study_hours']
        if study_hours < 0:
            raise forms.ValidationError('Время не может быть отрицательным')
        return study_hours

app/diary/views.py
from datetime import date, timedelta

from dateutil import parser
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from .forms import DiaryEntryForm


class DiaryEntryView(FormView):
    template_name = 'diary_entry.html'
    form_class = DiaryEntryForm
    success_url = '/diary/entry/success/'

    def get_initial(self):
        initial = super().get_initial()
        date_param = self.request.GET.get('date')
        if not date_param:
            initial['date'] = date.today().strftime('%Y-%m-%d')
        else:
            try:
                parsed_date = parser.parse(date_param)
                initial['date'] = parsed_date.strftime('%Y-%m-%d')
            except ValueError:
                initial['date'] = date.today().strftime('%Y-%m-%d')
        return initial

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url())

    def get(self, request, *args, **kwargs):
        form = DiaryEntryForm(initial=self.get_initial())
        return render(request, 'diary_entry.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = DiaryEntryForm(request.POST)
        if form.is_valid():
            form.save()
            # Обработка успешной отправки формы
            return redirect('success-url')
        return render(request, 'diary_entry.html', {'form': form})


def diary_entry_success(request):
    return render(request, 'diary_entry_success.html')


class DateListView(TemplateView):
    template_name = 'date_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        start_date = date(2023, 6, 1)
        end_date = date.today()
        date_range = [start_date + timedelta(days=x) for x in range((end_date - start_date).days + 1)]
        context['date_range'] = date_range
        return context

app/diary/templates/date_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container half-width">
        <br>
        <h1>Date List</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Weekday</th>
                    <th>Report</th>
                    <th>Statistics</th>
                </tr>
            </thead>
            <tbody>
                {% for date in date_range %}
                <tr>
                    <td>{{ date }}</td>
                    <td>{{ date|date:"l" }}</td>
                    <td> <a href="/diary/entry/">Fill Entry</a> </td>
                    <th> - </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/diary/templates/diary_entry.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5">
        <h1>Заполнение отчета</h1>
        <form method="GET" action="{% url 'diary:diary-entry' %}">
            {% csrf_token %}

            <div class="form-group">
                {{ form.date.label_tag }}
                {{ form.date }}
            </div>

            <div class="form-group">
                {{ form.steps.label_tag }}
                {{ form.steps }}
            </div>

            <div class="form-group">
                {{ form.study_hours.label_tag }}
                {{ form.study_hours }}
            </div>

            <button type="submit" class="btn btn-primary mt-3">Ввод данных</button>
        </form>
    </div>
{% endblock %}

app/diary/templates/diary_entry_success.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
    <title>Diary Entry Success</title>
</head>
<body>
    <h1>Diary Entry Successfully Saved</h1>
    <p>Your diary entry has been successfully saved.</p>
</body>
</html>