app/config/urls.py
"""config URL Configuration for the project
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from main.views import ProfileView

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('diary/', include('diary.urls')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='main:index'), name='logout'),
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lessons/', include('lessons.urls')),
]

app/main/urls.py
from django.urls import path

from .views import ContactView, CourseView, IndexView, SiteErrorView

# AboutView,

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('index/', IndexView.as_view(), name='index'),
    path('course/', CourseView.as_view(), name='course'),
    path('contact/', ContactView.as_view(), name='contact'),
    # path('profile/', ProfileView.as_view(), name='profile'),
    path('site_error/', SiteErrorView.as_view(), name='site_error'),
]

app/main/models.py
from django.db import models

# Create your models here.

app/main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from lessons.models import Lesson


class IndexView(TemplateView):
    template_name = 'index.html'


class CourseView(TemplateView):
    template_name = 'course.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получаем все уроки, сортированные по главам и порядку уроков внутри глав
        lessons = Lesson.objects.all().order_by('chapter', 'chapter_order')

        # Группируем уроки по главам
        chapters = {}
        for lesson in lessons:
            if lesson.chapter in chapters:
                chapters[lesson.chapter].append(lesson)
            else:
                chapters[lesson.chapter] = [lesson]


        context['chapters'] = chapters
        return context


class ContactView(TemplateView):
    template_name = 'contact.html'


class ProfileView(LoginRequiredMixin, View):
    template_name = 'profile.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'user': request.user})


class SiteErrorView(TemplateView):
    template_name = 'site_error.html'

app/main/templates/about.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <section id="about" class="about">
        <div class="container mt-5">
            <div class="row">
                <!-- Колонка для изображения -->
                <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
                    <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="Описание изображения">
                </div>
                <!-- Колонка для текста -->
                <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
                    <h3>О Проекте</h3>
                    <p class="fst-italic">
                        Наш проект посвящен обучению детей программированию на языке Python 3. <br> В современном мире, где технологии играют ключевую роль, умение программировать становится одним из наиболее ценных навыков.
                    </p>
                    <p>
                        Почему это так важно для детей? <br> Программирование развивает логическое мышление, учит решать сложные задачи и работать в команде. Оно также дает возможность детям быть творческими, создавая свои проекты и игры.
                    </p>
                    <ul>
                        <li><i class="bi bi-check-circle"></i> Развитие логического мышления и креативности.</li>
                        <li><i class="bi bi-check-circle"></i> Возможность создания собственных проектов и игр.</li>
                        <li><i class="bi bi-check-circle"></i> Формирование полезных привычек, таких как слепая печать и изучение языков.</li>
                    </ul>
                    <p>
                        Присоединяйтесь к нам и дайте вашему ребенку возможность стать частью цифрового будущего!
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/main/templates/contact.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<style>
  .map-iframe {
    margin: 20px auto; /* Увеличенный отступ сверху и снизу */
    padding: 0 20px; /* Увеличенные боковые отступы */
    display: block;
    width: 75%;
    height: 350px; /* Высоту можно настроить по желанию */
    border: none; /* Убираем рамку, если она есть */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Опционально добавляем тень для визуального выделения */
  }

  .email-link {
    color: #007BFF; /* Синий цвет для ссылок */
    font-weight: bold; /* Жирное начертание */
    text-decoration: none; /* Убрать подчеркивание */
  }

  .email-link:hover {
    text-decoration: underline; /* Подчеркивание при наведении */
  }
</style>

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Contact Us</h2>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">
        <br>
        <h3>Aby złożyć wniosek o szkolenie, napisz e-mail na adres: <a href="mailto:info@pykids.pl" class="email-link">info@pykids.pl</a></h3>
        <br>
        <h3>Co jest potrzebne, aby zacząć naukę?</h3>
        <ul>
          <li>Kurs jest przeznaczony dla dzieci w wieku od 11 do 15 lat.</li>
          <li>Kurs nie wymaga znajomości programowania ani matematyki.</li>
          <li>Kurs nie wymaga instalacji specjalnego oprogramowania, wystarczy komputer z przeglądarką internetową.</li>
        </ul>
      </div>
    </section><!-- End Contact Section -->


  </main><!-- End #main -->

{% endblock %}

app/main/templates/course.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<section id="about" class="about">
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
                <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="Zdjęcie kursu">
            </div>
            <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
                <h1>Plan kursu:</h1>
                {% for chapter, lessons in chapters.items %}
                <div>
                    <h2>{{ chapter.name }}</h2>
                    <ul>
                        {% for l in lessons %}
                        <div class="lesson">
                            <ul>
                                <li>
                                    <i class="bi bi-check-circle"></i>
                                    <a href="{% url 'lesson-detail' lesson_order=l.chapter_order %}">
                                        Lekcja {{ l.order }}: {{ l.title }}
                                    </a>
                                </li>
                            </ul>
                        </div>
                        {% endfor %}
                    </ul>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <section id="about" class="about">
        <div class="container mt-5">
            <div class="row">
                <!-- Колонка для изображения -->
                <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
                    <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="O programie PyKids">
                </div>
                <!-- Колонка для текста -->
                <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
                    <h4>PyKids: Bezpłatny interaktywny kurs programowania w Pythonie dla dzieci</h4>
                    <p class="fst-italic">
                        PyKids to kurs zaprojektowany specjalnie dla dzieci, aby mogły łatwo i przyjemnie nauczyć się programowania w języku Python. Nasz kurs kładzie nacisk na praktyczne zastosowanie metod nauki, które poprzez zabawę skupiają się na nauce niezbędnych aspektów języka.
                    </p>
                    <br>
                    <h4>Dlaczego PyKids?</h4>
                    <ul>
                        <li><i class="bi bi-check-circle"></i> Dostępność materiału: Wyjaśniamy skomplikowane koncepcje w prostym języku, aby każde dziecko mogło zrozumieć i używać materiałów edukacyjnych w praktyce.</li>
                        <li><i class="bi bi-check-circle"></i> Praktyczna orientacja: Wszystkie zadania i projekty są dostosowane do wieku i zdolności dzieci. Pomaga to nie tylko przyswoić materiał, ale również zastosować go w praktyce, tworząc własne gry i projekty.</li>
                        <li><i class="bi bi-check-circle"></i> Motywacja i zaangażowanie: Uczniowie sami tworzą gry i interaktywne projekty, co znacząco zwiększa zainteresowanie nauką.</li>
                        <li><i class="bi bi-check-circle"></i> Skupienie na wiedzy aplikacyjnej: Kurs koncentruje się na tych aspektach Pythona, które są najbardziej przydatne i interesujące dla dzieci, zapewniając niezbędne umiejętności do realizacji rzeczywistych zadań.</li>
                    </ul>
                    <h4>Co jest celem PyKids?</h4>
                     Celem PyKids jest nauka nie tylko programowania, ale również kreatywnego myślenia, pracy zespołowej oraz rozwiązywania skomplikowanych problemów.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/main/templates/site_error.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <section id="site-error" class="site-error">
        <div class="container mt-5">
            <div class="row justify-content-center text-center">
                <div class="col-lg-8">
                    <h1 class="mt-3">Wystąpił błąd</h1>
                    <p class="lead">
                        Na stronie wystąpił nieoczekiwany błąd. Przepraszamy za wszelkie niedogodności.
                    </p>
                    <p>
                        Proszę skontaktować się z administratorem strony, jeśli problem się powtórzy: info@pykids.pl
                    </p>
                    <div class="mt-4">
                        <a href="{% url 'main:home' %}" class="btn btn-primary">Wróć do strony głównej</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}