app/config/urls.py
"""config URL Configuration for the project
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from main.views import ProfileView

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('diary/', include('diary.urls')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='main:index'), name='logout'),
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('lessons/', include('lessons.urls')),
]

app/diary/urls.py
from django.urls import path

from .views import DateListView, DiaryEntryView, diary_entry_success

app_name = 'diary'

urlpatterns = [
    path('entry/', DiaryEntryView.as_view(), name='diary-entry'),
    # Добавляем путь с параметром для даты
    # path('entry/<slug:date>/', DiaryEntryView.as_view(), name='diary-entry-date'),
    path('entry/success/', diary_entry_success, name='diary-entry-success'),
    path('date-list/', DateListView.as_view(), name='date-list'),
]

app/main/urls.py
from django.urls import path

from .views import ContactView, CourseView, IndexView, SiteErrorView

# AboutView,

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('index/', IndexView.as_view(), name='index'),
    path('course/', CourseView.as_view(), name='course'),
    path('contact/', ContactView.as_view(), name='contact'),
    # path('profile/', ProfileView.as_view(), name='profile'),
    path('site_error/', SiteErrorView.as_view(), name='site_error'),
]

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>About - Mentor Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

<!-- Favicons -->
<link href="{% static 'assets/img/favicon.png' %}" rel="icon">
<link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
<link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
<link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
<link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

<!-- Template Main CSS File -->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

<!-- Custom static File
<link href="{% static 'custom.css' %}" rel="stylesheet">
-->
<link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">


  <style>
  .user-info {
    display: flex;
    flex-direction: column;
    align-items: center; /* Выравнивание элементов по центру */
  }

  .user-greeting {
    background-color: #ffffff; /* или любой другой цвет фона */
    border-radius: 5px; /* Скругление углов */
    padding: 5px 10px; /* Отступы внутри прямоугольника */
    margin-bottom: 2px; /* Отступ между прямоугольником и кнопкой */
    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2); /* Тень для прямоугольника */
  }

  .get-started-btn {
    /* Убедитесь, что ширина кнопки соответствует ширине прямоугольника */
    width: auto; /* или установите фиксированную ширину, если необходимо */
    text-align: center;
  }
</style>
  {% block extra_head %}{% endblock %}
</head>
<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="{% url 'main:index' %}">PYKIDS</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">

        <ul>
          <li><a href="{% url 'main:index' %}">Strona główna</a></li>
          <li><a href="{% url 'main:course' %}">Program kursu</a></li>
          <li><a href="{% url 'main:contact' %}">Kontakt</a></li>
<!--          <li class="dropdown"><a href="#"><span>Dziennik</span> <i class="bi bi-chevron-down"></i></a>-->
<!--            <ul>-->
<!--              <li><a href="{% url 'diary:date-list' %}">Dziennik</a></li>-->
<!--              <li><a href="{% url 'diary:date-list' %}">Moja statystyka</a></li>-->
<!--            </ul>-->
<!--          </li>-->
        </ul>

        <i class="bi bi-list mobile-nav-toggle"></i>
        <nav><!-- .navbar -->
          <div class="user-info d-flex flex-column align-items-end">
            {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="get-started-btn align-self-end flex-column">
                <div>{{ user.username }}</div>
                <div>Wyloguj się</div>
              </a>
            {% else %}
              <a href="{% url 'login' %}" class="get-started-btn align-self-end">Zaloguj się</a>
            {% endif %}
          </div>
        </nav>

      </nav>
    </div>
  </header><!-- End Header -->
  <br>
  <br>


  {% block content %}
      <main id="main">

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div data-aos="fade-up">
        <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" allowfullscreen></iframe>
      </div>

      <div class="container" data-aos="fade-up">

        <div class="row mt-6">
          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Location:</h4>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>info@example.com</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Call:</h4>
                <p>+1 5589 55488 55s</p>
              </div>

            </div>

          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">

            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Mentor</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  {% endblock %}


  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Pykids</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          Designed by Tier
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
<!--        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>-->
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
<!--        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>-->
<!--        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>-->
<!--        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>-->
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5">

  <h2 class="display-4">Profil użytkownika</h2>

  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">Informacje o użytkowniku:</h5>
      <p class="card-text">Nazwa użytkownika: {{ user.username }}</p>
      <p class="card-text">E-mail: {{ user.email }}</p>
      <!-- Dodaj dowolne inne informacje, które chcesz wyświetlić -->
    </div>
  </div>

</div>
{% endblock %}